// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB0f2pKA840U2v4AVmB7_K6fe10_9MiA0',
    appId: '1:699157037890:web:e6c194caf0d347b4eafedb',
    messagingSenderId: '699157037890',
    projectId: 'dance-imposter',
    authDomain: 'dance-imposter.firebaseapp.com',
    storageBucket: 'dance-imposter.firebasestorage.app',
    measurementId: 'G-2E850J9V5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj4trKsxMvRJztGJI8Tt8e_2Gn3ZbqDvk',
    appId: '1:699157037890:android:98f8b29133c04dd7eafedb',
    messagingSenderId: '699157037890',
    projectId: 'dance-imposter',
    storageBucket: 'dance-imposter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeQXcAXNHUOcI2Kbs48ky-JPQzUy26dPE',
    appId: '1:699157037890:ios:f538fec446831a3eeafedb',
    messagingSenderId: '699157037890',
    projectId: 'dance-imposter',
    storageBucket: 'dance-imposter.firebasestorage.app',
    iosBundleId: 'com.groupmanager.groupManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeQXcAXNHUOcI2Kbs48ky-JPQzUy26dPE',
    appId: '1:699157037890:ios:f538fec446831a3eeafedb',
    messagingSenderId: '699157037890',
    projectId: 'dance-imposter',
    storageBucket: 'dance-imposter.firebasestorage.app',
    iosBundleId: 'com.groupmanager.groupManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB0f2pKA840U2v4AVmB7_K6fe10_9MiA0',
    appId: '1:699157037890:web:eaf687581af8446ceafedb',
    messagingSenderId: '699157037890',
    projectId: 'dance-imposter',
    authDomain: 'dance-imposter.firebaseapp.com',
    storageBucket: 'dance-imposter.firebasestorage.app',
    measurementId: 'G-SKV3DJJ6Z1',
  );
}
